from rest_framework import serializers
from django.utils import timezone
from api.models import User, KYCSubmission, Document, Notification
from api.validators import validate_document_file

class UserRegistrationSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ['id', 'email', 'password', 'role']
        extra_kwargs = {
            'password': {'write_only': True}
        }

    def validate_role(self, value):
        if value != 'merchant':
            raise serializers.ValidationError(
                detail={
                    "error": True,
                    "message": "Only merchant registrations are allowed via this endpoint.",
                    "code": "invalid_role"
                }
            )
        return value

    def create(self, validated_data):
        # `create_user` internally correctly triggers `set_password` ensuring it is hashed.
        return User.objects.create_user(
            email=validated_data.get('email'),
            password=validated_data.get('password'),
            role=validated_data.get('role', 'merchant')
        )


class DocumentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Document
        fields = ['id', 'doc_type', 'file', 'uploaded_at']
        read_only_fields = ['id', 'uploaded_at']

    def validate_file(self, value):
        # Apply the standalone validator checking MIME type and Size.
        validate_document_file(value)
        return value


class KYCSubmissionSerializer(serializers.ModelSerializer):
    documents = DocumentSerializer(many=True, read_only=True)

    class Meta:
        model = KYCSubmission
        fields = [
            'id', 'full_name', 'email', 'phone', 
            'business_name', 'business_type', 'monthly_volume_usd',
            'status', 'submitted_at', 'created_at', 'updated_at',
            'documents'
        ]
        # Notice `merchant` is entirely omitted from `fields` to prevent the caller manually supplying it.
        # It will be cleanly injected in `serializer.save(merchant=request.user)` inside the view.
        read_only_fields = ['status', 'submitted_at', 'created_at', 'updated_at']


class ReviewerSubmissionSerializer(serializers.ModelSerializer):
    documents = DocumentSerializer(many=True, read_only=True)
    is_at_risk = serializers.SerializerMethodField()

    class Meta:
        model = KYCSubmission
        fields = [
            'id', 'merchant', 'full_name', 'email', 'phone', 
            'business_name', 'business_type', 'monthly_volume_usd', 
            'status', 'submitted_at', 'created_at', 'updated_at', 
            'reviewer', 'reviewer_note', 'documents', 'is_at_risk'
        ]

    def get_is_at_risk(self, obj):
        """
        Dynamically calculates if the submission has been stuck in 
        processing ('submitted' or 'under_review') for greater than 24 hours.
        """
        if obj.submitted_at and obj.status in ['submitted', 'under_review']:
            elapsed_time = timezone.now() - obj.submitted_at
            # 86400 seconds = 24 hours
            return elapsed_time.total_seconds() > 86400
        return False


class NotificationSerializer(serializers.ModelSerializer):
    class Meta:
        model = Notification
        fields = ['id', 'merchant', 'event_type', 'timestamp', 'payload']
        # Notifications are exclusively generated by the system and state machines.
        read_only_fields = ['id', 'merchant', 'event_type', 'timestamp', 'payload']
